[project]
name = "toggle-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastmcp>=2.10.5",
    "pydantic-settings>=2.10.1",
    "requests>=2.32.4",
]
